### ISSUE TITLE
Deleted items not deleted

### ISSUE THREAD

**Issue by pramsky** [nylas/nylas-mail#2706]
##### Are there any related issues?

...
##### What operating system are you using?

OSX
##### What version of N1 are you using?

...
Version 0.4.47-3a2a94c (0.4.47-3a2a94c)
## 

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?

... No
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

... Exchange
##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
I deleted a large number of messages ( around 600 ) and it showed as deleted from my Nylas Inbox. I went to the Office365 web app and all the messages were still there. 

So I deleted them on the web portal, then when I went back to Nylas, they are back in Nylas.

Even after I cleared the Email cache and they are back in Nylas. 
## 

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?

...

**Comment by fibric** [comment]
Same here.

Version 0.4.47-3a2a94c (0.4.47-3a2a94c)
macOS 10.12 Beta (16A270f)

I can delete, N1 deletes the Email, shows the deletion success notification (with undo option), refreshes the inbox and the Email shows up again. It all started with the current version 0.4.47-3a2a94c (0.4.47-3a2a94c).

**Comment by pramsky** [comment]
All providers are affected as well. Initially it looked like it was just Exchange, but I verified that its an issue with GMail as well.

**Comment by hallamoore** [comment]
Merging with #781. Feel free to post comments on that issue, thanks!

**Comment by jstejada** [comment]
Reopening this because there seems to be a problem with deleting specifically.

From user reports:

(1) Emails I delete from the inbox often pop up again shortly after they have been deleted, usually with no message content and a line of text saying the message content is not available. (2) Many (not all) emails I have deleted are never actually deleted in Gmail, but are simply archived. N1 v0.4.45-7637265 (and all earlier versions up to this point).

Possible solution:

if you've ever used Google Inbox, even once just to try it out, it has settings for bundling email. As soon as I went in and turned those off, my sync actions worked perfectly.

This might be a duplicate of #2725. Will merge when we know for sure

**Comment by pramsky** [comment]
Well I do get a lot of emails over exchange, I have 2 instances of Nylas running (desktop and laptop). I delete on one, but then I have to delete it all over again on the other AND on exchange web portal.

Since its a sync issue, even things which are taken care of by rules on the Nylas client are not updated either.

**Comment by fibric** [comment]
It's not related to bundled messages because I can't delete emails of any provider.
I uploaded a video showcasing the [Email deletion bug](https://youtu.be/ECvtQ6SPiEw).

**Comment by rawjam** [comment]
I'm getting the same thing. This has been an issue for me for age (2months plus). Deleting almost always causes the email to immediately bounce back into the N1 inbox. Sometimes I have to attempt deletion 2 or 3 times before it works... then, when I have finally deleted it, i often find that the email (although now deleted from my N1 inbox) is still in my Outlook or Gmail inbox... i.e. it clearly hasn't propagated.

**Comment by Tomsgu** [comment]
Same issue as @fibric pointed here still with a new release 0.4.49-c9c04b7.

**Comment by pramsky** [comment]
Confirmed issue still exists.

**Comment by SGillessen** [comment]
same issue here, looks exactly as shown in https://github.com/nylas/N1/issues/2706#issuecomment-239541674 by @fibric.

here is a screenshot from the console output.

https://slack-files.com/T04TLAQ2T-F23406Z9N-22653ad2e4

can't delete, archive, mark as spam. Also no sync to any email account.

no third party plugins active/installed, just built-in ones.

Win 10
Nylas 4.49

Also had Jackie on Slack look into it:
![n1 help nylas community slack](https://cloud.githubusercontent.com/assets/10210934/17829357/52dbf61c-66ac-11e6-98fe-fc74e9596626.png)

**Comment by fibric** [comment]
I solved the issue for me by deleting the `~/.nylas` folder. Of course, I had to re-setup all my accounts and plugins, but I can delete emails again :-)

But it seems the delete icon isn't clickable sometimes. I have to use the context menu.

**Comment by rawjam** [comment]
I took your advice and deleted the ~/.nylas folder. I re-added all accounts and still, deleted items are not deleting. What feels like 80% of the time, I press delete and the message immediately re-appears in the inbox. So frustrating.

**Comment by rawjam** [comment]
Ugh, this is driving me insane. Every other email i delete just pops right back into my inbox. I followed your advice and tried deleting the ~/.nylas folder and nothing improved. As of 2 hrs ago I have now clean installed macOS Sierra and still i am plagued with the phantom deleting issue. 

Please please can someone tell us what the state of play is here? Is this issue being taken seriously.

**Comment by pramsky** [comment]
Same issue still a month in, I have switched away from Nylas till this is resolved.

**Comment by rawjam** [comment]
Completely agree. I just find the communication on this topic so frustrating. If 'every' email that a lot of us are deleting are simply re-appearing back in the inbox, then clearly the service is majorly at fault for a large number of people. It may be being prioritised at the moment, but it just doesn't feel like it is.

**Comment by Tomsgu** [comment]
Yeah the main reason I switched to nylas was to have a stable email client with a nice simple gui in addition. Now it seems that they concentrate more on their cloud(and it's reasonable), that is working fine, isn't it? But the free version is in totally broken state, so nobody can't use it.

**Comment by willwright82** [comment]
Same issue here for deleting on a Gmail account: Deleting a message applies the label and sends it to Trash in Nylas, but message is still unread and in the inbox on other clients (Spark on iOS and Gmail Web). Will have to switch away from Nylas until this is solved. 😞

**Comment by emadow** [comment]
I, too, am having this issue. Any word on a fix?

**Comment by juanscv** [comment]
Sometimes I get the same issue.

I try to delete an email and it either won't delete, or it disappears from Inbox list only to show right back up in 2 seconds. 

I usually have to quit the app and reopen it before I can truly delete them.

MacOS Sierra
Nylas 0.4.56-816edde (happened on previous versions too)

**Comment by rawjam** [comment]
I've stopped using N1 now. The problem was constant for me and didn't appear to be taken seriously by Nylas.

On Sun, Oct 9, 2016 at 5:53 pm, Juan Sebastian Camargo Visbal <notifications@github.com> wrote:
Sometimes I get the same issue.

I try to delete an email and it either won't delete, or it disappears from Inbox list only to show right back up in 2 seconds.

I usually have to quit the app and reopen it before I can truly delete them.

MacOS Sierra
Nylas 0.4.56-816edde (happened on previous versions too)

**Comment by DannyDouglass** [comment]
I'm having this issue as well. as someone that drives for inbox zero everyday this is a major issue. any update from the Nylas team?

**Comment by benjamindell** [comment]
I'm sorry to say Danny, that this issue has been around for ages. I've been plagued with it for many many months. It doesnt look like Nylas are taking it too seriously though. I got so frustrated that I stopped using N1 a couple of months ago. Just too damn painful every day having to double delete things. I just couldn't trust the software anymore.

**Comment by pramsky** [comment]
I stopped using N1 as well. Would love to have a single cross platform email client between my various systems and would be back on N1 in a minute if this issue is resolved. At the very least get some response back from the developers, even if it is to say, "Hey we know this is an issue"

**Comment by DannyDouglass** [comment]
After updating to the latest stable release `0.4.201-4cdd3ed`, I now have multiple messages that I can't delete. Not to mention archiving and scheduling a message takes _several_ seconds. Anyone on the core team have an update?

**Comment by DannyDouglass** [comment]
no longer care about this - switched to Spark

**Comment by fibric** [comment]
N1 is dead.
Airmail3 is great 👍

**Comment by ntang** [comment]
Also seeing the same issues - I delete an email in Nylas and it pops back up a few seconds later.  This is for a gmail account that I _am_ using Inbox with.  No, not planning on turning off Inbox in the near future until I'm satisfied that Nylas is working properly.

**Comment by jakeparis** [comment]
I turned off all bundling in Inbox, and still have the same problem. I also tried marking the mail as unread and read again. Neither worked.  Various emails, upon deletion, immediately reappear in the inbox. No matter how many times I try, they won't go away.

**Comment by jstejada** [comment]
hi all-- we're really sorry for the delays in getting this issue solved! This should not be the case in Nylas Basic. We're going to look into it right away. @ntang @jakeparis, what version of Nylas Mail are you using? By deleting you mean moving to trash?

Thanks for your patience!

**Comment by jcjan** [comment]
Same here - I was having the issue in N1 on my Mac. Downloaded Nylas Mail today (1.0.8) and am still having the same issue. I'm on the free Basic plan.

It only seems to happen when doing "Move to Trash" on certain emails in one of my Gmail accounts on which I had never enabled Inbox. I think it had happened when trying to "Archive" at one point too, although I just tried that again and it worked correctly. Enabling Inbox and turning off bundling didn't change anything.

**Comment by jstejada** [comment]
hmm @jcjan thanks for the additional details. That's really weird because the sync logic that's running on Nylas Mail Basic (1.0.8) is completely different from the one running in previous versions of Nylas Pro (N1), which might suggest that it is due to some specific setting in some accounts.

Are there any other details you have about the specific emails that don't get deleted? What do you mean by enabling Inbox?

**Comment by jakeparis** [comment]
I just downloaded the Nylas Mail Basic today and setup a new Nylas account.  

By "enabling Inbox" I meant that [in this comment](https://github.com/nylas/N1/issues/2706#issuecomment-239515269) you suggested that if we've ever used Google Inbox, the bundling feature might be to blame. I've turned off all bundling. 

Happy to help with account details if that helps track down the issue.

**Comment by jstejada** [comment]
Ah great, thanks @jakeparis ! Sorry I missed that!

**Comment by ntang** [comment]
@jstejada I'm on the latest version, 1.0.8, just installed it today.

**Comment by jcjan** [comment]
@jstejada I just mean that I visited inbox.google.com for the first time with that account, and then went into the settings and unchecked all the bundling options. Not sure if that triggers Gmail to start handling anything differently or not.

So far I've mostly noticed it with notification emails from jira, which are usually threads of multiple messages.

**Comment by jakeparis** [comment]
I see the Nylas is attempting to sync my account, seems that it's doing a big sync, probably an initial sync. The main view says "Looking for more messages..." I wonder if that's playing some role in the problem. 

It seems that if I check the box and click the trashcan icon at the top, the mail comes right back. However, it seems that if I drag the mail to the left bar "Trash", it stays deleted. _Though_, it does reappears briefly in the mail list, and then disappears again.

**Comment by jstejada** [comment]
@ntang @jcjan @jakeparis thanks for the additional details! Do any of you have any setting to make moving to trash permanently delete messages?

@jakeparis, where it says "Looking for more messages...", is that on the inbox? or another folder? what do you mean by "checking the box"? on the lower left corner, if you click "Syncing your mail", what does your sync progress look like?

if you open the activity window via `cmd+alt+w`, then open dev tools via `cmd+alt+i`, and select the Console tab, do you see any errors?

**Comment by jakeparis** [comment]
No errors in the console.

"looking for more messages" is in the inbox. By "checking the box", I mean clicking/selecting the checkbox to the left of the message in the inbox view.

My sync progress looked like Spam and Trash were still working.

**Comment by jstejada** [comment]
@jakeparis and this is from messages that you are deleting from your inbox?

**Comment by jstejada** [comment]
we've detected the issue on Nylas Basic and working on a fix. We'll push a new update soon!

**Comment by jakeparis** [comment]
Yes, I was deleting messages from my inbox.

**Comment by jakeparis** [comment]
@jstejada Sorry to say the issue persists with today's update. I now have Nylas Basic 1.0.9 and still there are some mails I can't delete. You can see here the mail coming back after deletion:
![zombie-mail](https://cloud.githubusercontent.com/assets/7408985/22112850/7a8ce380-de32-11e6-9066-ba1cfa9cf8e5.gif)

Then finally, after multiple tries, here you can see the mail coming back for a millisecond then going away again. 
![flicker-zombie](https://cloud.githubusercontent.com/assets/7408985/22113003/edbdf7b8-de32-11e6-9cda-5c612daa5903.gif)
I'm not sure if the different method of deletion (drag-to-trash vs. pressing trash button) had anything to do with it working finally, but I have had the same problem with the drag-to-trash method before the update.

**Comment by djdiaz** [comment]
I'm also seeing the behavior @jakeparis is seeing in the new Nylas Mail. However, this is slightly different from what I see in the original N1. In the new app, the email often reappears only to vanish again in under a second, and other times reappears and has to be deleted again. In N1, the email will reappear in the inbox, but will usually have a note saying it has been deleted when it is selected.

**Comment by jstejada** [comment]
hi @jakeparis @djdiaz thanks for the updates! We are still working on the fixes and will push them out soon. Thanks for your patience!

**Comment by ntang** [comment]
@jstejada deletions _seem_ to be working for me now (but I haven't dug in deeply - I just mean after I delete an email in Nylas it seems to stay deleted), but even though the client said it finished syncing my email, the numbers don't line up w/ what gmail says.  Disclaimer: I have a *lot* of mail and I'm terrible about email 'hygiene', so I have over 37k unread emails in gmail.  But according to Nylas, I have over 50k unread emails in gmail.  I know sometimes gmail can provide estimated counts instead of exact counts, and I've been cleaning up my inbox and paring things down over the past few days, so I figured I'd give it a while and see what happens.

However, at this point it seems to be "up to date" and still way off in the counts.  For another example, I just emptied my trash in gmail (so there's 0 in there) and Nylas reports 4102 (unread?) emails in there.

Gmail:
<img width="516" alt="screenshot 2017-01-19 16 08 14" src="https://cloud.githubusercontent.com/assets/470727/22125425/a2c97fc8-de61-11e6-9dca-2471c242fd39.png">

Nylas:
<img width="140" alt="screenshot 2017-01-19 16 09 48" src="https://cloud.githubusercontent.com/assets/470727/22125442/b665cbcc-de61-11e6-8c76-3c9573301ed0.png">

**Comment by ntang** [comment]
D'oh.  It's still happening.  Less frequently, now, but a few messages I've deleted popped back into my inbox.  (Running 1.0.10.)

**Comment by jstejada** [comment]
hi @ntang thanks for the info. We haven't pushed the fix in 1.0.10. I will let you know as soon as we do so!

**Comment by jstejada** [comment]
Hi all, just checking in to let you know that the fixes for deleting messages will probbaly be released early next week

**Comment by Naatan** [comment]
Fwiw it seems for me the issue is related to threads. It seems to delete the last message in the thread, then later shows the thread again but with the previous "last message" deleted.

**Comment by jcjan** [comment]
I have also found that a) it happens specifically with threaded messages, and b) it happens when using the "trash" button, but not when dragging the message to the trash folder.

Thanks for giving attention to this and looking forward to the fix!

**Comment by fonnesbeck** [comment]
For me, this does occur with threaded messages when using the trash icon as well. The entire thread re-appears after deleting, in my case. Drag and drop or swiping does appear to delete the thread properly.

**Comment by jstejada** [comment]
hi everyone, we've released version 1.0.15 of Nylas Mail, which should improve these issues with moving threads to trash. Let me know if you are still seeing issues after the update. Thanks everyone for your patience on this issue!

**Comment by fonnesbeck** [comment]
I am on 1.0.15 (updated this afternoon) and I am still seeing the issue, unfortunately.

**Comment by jstejada** [comment]
@fonnesbeck how soon after deleting does it re-appear? if you open the activity window (`cmd+alt+i`), and select the `Client Tasks` tab, do you see any failed tasks?

**Comment by fonnesbeck** [comment]
A few moments later, but *after* the "syncing your mailbox" message disappears. Just happened now with the message notifying me of your response.

I don't see any errors in the Client Tasks window, just `ChangeUnreadTask (ID: 7c95) SUCCESS (PROCESSING REMOTE)`

**Comment by jstejada** [comment]
@fonnesbeck thanks! 
are you running `1.0.15` or `1.5`? (sorry for the confusion, just want to make sure)
so, if you try moving to trash, do you see any `ChangeLabelsTask` or `ChangeFolderTask` succeed or fail?

**Comment by fonnesbeck** [comment]
Running Version 1.0.15 (1.0.15)

**Comment by fonnesbeck** [comment]
Also, I noticed this happens for archiving as well as deleting. Works with drag and drop, but not with the icons.

**Comment by Naatan** [comment]
I thought there was a fix coming for this? I don't understand how this isn't a bigger priority, it undermines everything about your application.

**Comment by jakeparis** [comment]
Confirming that 1.0.20 does _not_ fix the issue. There are currently multiple (brand new) threads in my inbox that will keep resurrecting themselves. 

Agree with @Naatan , this renders the app unusable.

**Comment by jstejada** [comment]
hi @Naatan , @jakeparis , @fonnesbeck , I'm sorry to hear that 1.0.20 doesn't fix the error. Do you see any error messages? Does this only happen with specific threads?

**Comment by Naatan** [comment]
I can't tell if there are errors because when I try to open the log Nylas tells me I don't have permission and to contact a computer or network admin. Kinda hard to tell what to do if it doesn't tell me the path though.

As for specific threads, it appears to happen only with threaded emails, doesnt happen with single emails. Just like before.

**Comment by jstejada** [comment]
@Naatan thanks! When deleting fails, do you see any error dialogs come up? does the thread contain replies?

**Comment by Naatan** [comment]
No error dialog. The threads I'm seeing don't contain replies but rather "similar emails". eg. I have 2 emails notifying me about a mailing list membership and they get grouped together.

**Comment by jstejada** [comment]
hey @Naatan , @jakeparis , @fonnesbeck , @jcjan , in order to diagnose this, could you do the following:

1. Open the Activity Window via `cmd+alt+i`
2. In the Activity Window, open Dev Tools via `cmd+alt+w`
3. Select the `Console` tab

4. Try to delete the thread that wont go away

4. Send me a screenshot of your `Console` from the Activity Window as it is

5. Then select the `Filter` icon
![image](https://cloud.githubusercontent.com/assets/1271509/22381429/6bbd79f6-e476-11e6-8a06-a5e94acd91b1.png)

6. Then Filter by Errors
<img width="870" alt="screen shot 2017-01-27 at 9 53 41 am" src="https://cloud.githubusercontent.com/assets/1271509/22381496/ad948504-e476-11e6-951e-719abbc2a1f9.png">

7. Send me a second screenshot of your `Console` filtered by errors

If you prefer not to share the screenshots here, feel free to send them to support@nylas.com and mention Juan

Thanks!

**Comment by laughedelic** [comment]
I'm not so sure that it happens only with threads. Sometimes I see that a single message I delete reappears in the inbox and then disappears again.

**Comment by Naatan** [comment]
@jstejada no errors in the console, so nothing to send.

**Comment by Naatan** [comment]
Note the email is gone from the list and then just returns seconds later.

**Comment by laughedelic** [comment]
I also don't see any errors in the console.

**Comment by djdiaz** [comment]
I see it with single emails constantly. And let's not forget the similar bug in N1. I see it in both Nylas Mail and N1 (more so in N1), and it seems like they shouldn't be conflated as they are different bugs.

**Comment by jstejada** [comment]
thanks! @Naatan @laughedelic @djdiaz -- just to make sure, this is in the Conolse in the Activity Window right? (not the Console in the main window)

**Comment by laughedelic** [comment]
@jstejada before I missed this, but now I checked the console in the Activity window and there are literally no new console messages appearing when the bug appears. Observed at least 5 times just now.

**Comment by jstejada** [comment]
hey everyone, we've identified the issue and we're working on a fix. The fix should go out soon!

**Comment by djdiaz** [comment]
@jstejada Did you fix the bug just in the new Nylas Mail, or also in N1?

**Comment by jstejada** [comment]
@djdiaz this is for nylas mail

**Comment by djdiaz** [comment]
@jstejada I would suggest opening a new issue for Nylas Mail. This _is_ the issue for N1.

**Comment by Naatan** [comment]
Wait what? I thought N1 became Nylas Mail? I'm seeing this issue on Nylas Mail.

**Comment by djdiaz** [comment]
@Naatan Nylas Pro is still N1.

**Comment by Naatan** [comment]
So this whole issue is only for Nylas Pro and will not mean any change for Nylas Mail? I'm a little bit perplexed since an issue like this would logically affect both, seeing as they would still share a codebase I'd  imagine.

**Comment by djdiaz** [comment]
@Naatan As I understand it, Nylas Mail doesn't sync mail via the Nylas cloud services, but does it locally. N1 still uses the cloud services. So the sync mechanisms would be completely different. (I could be wrong about this.) @jstejada is saying that the bug in Nylas Mail is being fixed, but not in Nylas Pro (N1).

**Comment by Naatan** [comment]
@djdiaz your comment here seems to imply the inverse of what you just said - https://github.com/nylas/nylas-mail/issues/2706#issuecomment-277185768

ie. this ticket is fixing N1 but not Nylas Mail. Which is the opposite of what you just said.

**Comment by djdiaz** [comment]
@Naatan Not sure how you read that from the comments.

**Comment by Naatan** [comment]
Ok, just to be clear though - this issue is for Nylas Mail or N1? Since I'm confused now.

**Comment by djdiaz** [comment]
@Naatan The _issue_ is for N1 (reported long before Nylas Mail existed). The _fix_ that has been reported is for Nylas Mail, not N1.

**Comment by Naatan** [comment]
Gotcha, thanks.

**Comment by jstejada** [comment]
@Naatan , correct-- as @djdiaz mentioned, the issue appears to be for both Nylas Mail and Nylas Pro (previous N1), and the bug is being fixed in Nylas Mail.

**Comment by jstejada** [comment]
hi folks, we've just released **Nylas Mail v1.0.21** and this issue should be fixed in that version. If you encounter it again, please let us know by posting here and reopening this issue.


-------------------------
If you are still seeing this error in Nylas Pro (N1) v1.5.0, I've opened a separate issue to track the problem on Nylas Pro v.1.5.0: https://github.com/nylas/nylas-mail/issues/3261. Please post there with any additional details if you still see the error on Nylas Pro (N1) v.1.5.0

Thanks again for your patience!

**Comment by Naatan** [comment]
Thanks guys, updated to 1.0.21 and - emails stay deleted :D Finally I can use Nylas Mail again :)

**Comment by laughedelic** [comment]
I diced to try out Nylas Mail, because in Pro this bug is too annoying. I'm on Nylas Mail 1.0.27 and I still see this problem. Messages reappear in the inbox, but not immediately like in Pro, after some time, it's even harder to notice.
