### ISSUE TITLE
Default signature attached for accounts without signature specified

### ISSUE THREAD

**Issue by fonnesbeck** [nylas/nylas-mail#3234]
I have a signature specified for one of my accounts, but have nothing for my other accounts (I prefer not to have signatures on personal emails). However, when I try to send a message with one of these accounts with no signature specified, the defualt Nylas signature is still attached. Is this a bug, or is there a setting I am missing?

Running 1.0.15 on mac OS 10.12.3

**Comment by emadow** [comment]
Also running into this error. Just moved to _Mail_ from _Pro_.

Version 1.0.21 (1.0.21) / MacOS 10.12.3

**Comment by sheatsb** [comment]
I'm still running into this in N1 version 1.5.0 **and** Nylas Mail 1.0.32.

**Comment by sachinag** [comment]
This should be fixed in 1.0.32 but sadly still in 1.5.0 :(

**Comment by sheatsb** [comment]
@sachinag  Could I use 1.0.32 as a pro user? What's the difference anymore?

**Comment by sachinag** [comment]
http://nylas.com/pricing has the differences - You can use 1.0.32 if you prefer, but a lot of those features aren't there.

**Comment by shenanigans12** [comment]
We are on freaking 2.0.32 and this is STILL an issue? I give up Nylas, it was fun while it lasted, but I'm going to greener pastures.
